# Source Repository Pipeline
stages:
  - build_and_deploy
  - notify_escrow

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build_job:
  stage: build_and_deploy
  image: maven:3.9.6-eclipse-temurin-17
  script: |
    echo "Compiling Consumer App..."
    mvn clean package -DskipTests
    echo "Build successful."
  artifacts:
    paths:
      - target/*.jar

notify_job:
  stage: notify_escrow
  image: curlimages/curl
  script: |
    echo "Simulating notifying RabbitMQ..."
    PAYLOAD=$(cat <<PAYLOAD_EOF
    {
      "relativePath": "${CI_PROJECT_PATH}",
      "branch": "${CI_COMMIT_REF_NAME}",
      "commitHash": "${CI_COMMIT_SHA}",
      "buildVariables": {
        "CI_PIPELINE_ID": "${CI_PIPELINE_ID}"
      }
    }
    PAYLOAD_EOF
    )
    curl -u guest:guest \
      -H "content-type:application/json" \
      -X POST -d '{"properties":{},"routing_key":"build.queue","payload_encoding":"string","payload":"'"$(echo "$PAYLOAD" | sed 's/"/\\"/g' | tr -d '\n')"'"}' \
      http://escrow-rabbitmq:15672/api/exchanges/%2f/amq.default/publish
    echo "Message sent to RabbitMQ successfully."
  needs: ["build_job"]
